import 'package:zigee_app/models/reservation.dart';
import 'package:zigee_app/models/room.dart';
import 'package:zigee_app/models/dummy/dummy_rooms.dart';

class DummyReservations {
  static final List<Reservation> reservations = [
    Reservation(
      id: 'res_001',
      uid: 'uid_001',
      userId: 'user_001',
      roomId: 'room_001',
      title: '팀 미팅',
      startTime: DateTime.now().subtract(const Duration(hours: 2)),
      endTime: DateTime.now().subtract(const Duration(hours: 1)),
      purpose: '주간 팀 미팅 및 프로젝트 진행 상황 공유',
      status: ReservationStatus.confirmed,
      attendeeCount: 5,
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      updatedAt: DateTime.now().subtract(const Duration(days: 2)),
    ),
    Reservation(
      id: 'res_002',
      uid: 'uid_002',
      userId: 'user_002',
      roomId: 'room_002',
      title: '기획 회의',
      startTime: DateTime.now().subtract(const Duration(hours: 4)),
      endTime: DateTime.now().subtract(const Duration(hours: 3)),
      purpose: '2024년 4분기 사업 계획 수립',
      status: ReservationStatus.confirmed,
      attendeeCount: 8,
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
      updatedAt: DateTime.now().subtract(const Duration(days: 4)),
    ),
    Reservation(
      id: 'res_003',
      uid: 'uid_003',
      userId: 'user_003',
      roomId: 'room_003',
      title: '클라이언트 미팅',
      startTime: DateTime.now().subtract(const Duration(minutes: 30)),
      endTime: DateTime.now().add(const Duration(minutes: 30)),
      purpose: '신규 프로젝트 제안서 발표',
      status: ReservationStatus.confirmed,
      attendeeCount: 3,
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      updatedAt: DateTime.now().subtract(const Duration(hours: 2)),
    ),
    Reservation(
      id: 'res_004',
      uid: 'uid_004',
      userId: 'user_004',
      roomId: 'room_004',
      title: '브레인스토밍',
      startTime: DateTime.now().subtract(const Duration(minutes: 15)),
      endTime: DateTime.now().add(const Duration(minutes: 45)),
      purpose: '신제품 아이디어 발굴 세션',
      status: ReservationStatus.confirmed,
      attendeeCount: 6,
      createdAt: DateTime.now().subtract(const Duration(hours: 8)),
      updatedAt: DateTime.now().subtract(const Duration(hours: 4)),
    ),
    Reservation(
      id: 'res_005',
      uid: 'uid_005',
      userId: 'user_005',
      roomId: 'room_001',
      title: '디자인 리뷰',
      startTime: DateTime.now().add(const Duration(minutes: 10)),
      endTime: DateTime.now().add(const Duration(hours: 1, minutes: 10)),
      purpose: 'UI/UX 디자인 최종 검토',
      status: ReservationStatus.confirmed,
      attendeeCount: 4,
      createdAt: DateTime.now().subtract(const Duration(hours: 12)),
      updatedAt: DateTime.now().subtract(const Duration(hours: 6)),
    ),
    Reservation(
      id: 'res_006',
      uid: 'uid_006',
      userId: 'user_006',
      roomId: 'room_005',
      title: '임원진 회의',
      startTime: DateTime.now().add(const Duration(hours: 1)),
      endTime: DateTime.now().add(const Duration(hours: 3)),
      purpose: '분기별 성과 검토 및 향후 전략 논의',
      status: ReservationStatus.confirmed,
      attendeeCount: 12,
      createdAt: DateTime.now().subtract(const Duration(days: 7)),
      updatedAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    Reservation(
      id: 'res_007',
      uid: 'uid_007',
      userId: 'user_007',
      roomId: 'room_002',
      title: '개발팀 스프린트 리뷰',
      startTime: DateTime.now().add(const Duration(hours: 2)),
      endTime: DateTime.now().add(const Duration(hours: 3)),
      purpose: '스프린트 완료 항목 검토 및 데모',
      status: ReservationStatus.confirmed,
      attendeeCount: 9,
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      updatedAt: DateTime.now().subtract(const Duration(hours: 18)),
    ),
    Reservation(
      id: 'res_008',
      uid: 'uid_008',
      userId: 'user_008',
      roomId: 'room_006',
      title: '1:1 멘토링',
      startTime: DateTime.now().add(const Duration(hours: 4)),
      endTime: DateTime.now().add(const Duration(hours: 5)),
      purpose: '신입사원 온보딩 및 멘토링',
      status: ReservationStatus.pending,
      attendeeCount: 2,
      createdAt: DateTime.now().subtract(const Duration(hours: 6)),
      updatedAt: DateTime.now().subtract(const Duration(hours: 3)),
    ),
    Reservation(
      id: 'res_009',
      uid: 'uid_009',
      userId: 'user_009',
      roomId: 'room_007',
      title: '교육 세션',
      startTime: DateTime.now().add(const Duration(hours: 6)),
      endTime: DateTime.now().add(const Duration(hours: 8)),
      purpose: '보안 교육 및 컴플라이언스 교육',
      status: ReservationStatus.cancelled,
      attendeeCount: 15,
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
      updatedAt: DateTime.now().subtract(const Duration(hours: 1)),
    ),
    Reservation(
      id: 'res_010',
      uid: 'uid_010',
      userId: 'user_010',
      roomId: 'room_001',
      title: '주간 스탠드업',
      startTime: DateTime.now().add(const Duration(days: 1, hours: 9)),
      endTime: DateTime.now().add(
        const Duration(days: 1, hours: 9, minutes: 30),
      ),
      purpose: '주간 업무 공유 및 이슈 논의',
      status: ReservationStatus.confirmed,
      attendeeCount: 7,
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      updatedAt: DateTime.now().subtract(const Duration(hours: 12)),
    ),
    Reservation(
      id: 'res_011',
      uid: 'uid_011',
      userId: 'user_011',
      roomId: 'room_002',
      title: '고객 미팅',
      startTime: DateTime.now().add(const Duration(days: 1, hours: 14)),
      endTime: DateTime.now().add(const Duration(days: 1, hours: 16)),
      purpose: '고객 요구사항 분석 및 솔루션 제안',
      status: ReservationStatus.confirmed,
      attendeeCount: 5,
      createdAt: DateTime.now().subtract(const Duration(hours: 20)),
      updatedAt: DateTime.now().subtract(const Duration(hours: 8)),
    ),
    Reservation(
      id: 'res_012',
      uid: 'uid_012',
      userId: 'user_012',
      roomId: 'room_004',
      title: '워크숍',
      startTime: DateTime.now().add(const Duration(days: 7, hours: 10)),
      endTime: DateTime.now().add(const Duration(days: 7, hours: 17)),
      purpose: '팀 빌딩 및 창의성 향상 워크숍',
      status: ReservationStatus.confirmed,
      attendeeCount: 20,
      createdAt: DateTime.now().subtract(const Duration(days: 14)),
      updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    ),
    Reservation(
      id: 'res_013',
      uid: 'uid_013',
      userId: 'user_013',
      roomId: 'room_001',
      title: '프로젝트 킥오프',
      startTime: DateTime.now().subtract(const Duration(days: 1, hours: 3)),
      endTime: DateTime.now().subtract(const Duration(days: 1, hours: 1)),
      purpose: '신규 프로젝트 시작 미팅',
      status: ReservationStatus.confirmed,
      attendeeCount: 6,
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
      updatedAt: DateTime.now().subtract(const Duration(days: 2)),
    ),
    Reservation(
      id: 'res_014',
      uid: 'uid_014',
      userId: 'user_014',
      roomId: 'room_003',
      title: '코드 리뷰',
      startTime: DateTime.now().subtract(const Duration(days: 2, hours: 2)),
      endTime: DateTime.now().subtract(const Duration(days: 2, hours: 1)),
      purpose: '주요 기능 코드 리뷰 및 개선 방안 논의',
      status: ReservationStatus.confirmed,
      attendeeCount: 4,
      createdAt: DateTime.now().subtract(const Duration(days: 7)),
      updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    ),
    Reservation(
      id: 'res_015',
      uid: 'uid_015',
      userId: 'user_015',
      roomId: 'room_005',
      title: '월간 성과 발표',
      startTime: DateTime.now().subtract(const Duration(days: 3, hours: 4)),
      endTime: DateTime.now().subtract(const Duration(days: 3, hours: 2)),
      purpose: '월간 업무 성과 발표 및 피드백',
      status: ReservationStatus.confirmed,
      attendeeCount: 15,
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
      updatedAt: DateTime.now().subtract(const Duration(days: 4)),
    ),
    Reservation(
      id: 'res_016',
      uid: 'uid_016',
      userId: 'user_016',
      roomId: 'room_002',
      title: '기술 세미나',
      startTime: DateTime.now().subtract(const Duration(days: 4, hours: 3)),
      endTime: DateTime.now().subtract(const Duration(days: 4, hours: 1)),
      purpose: '최신 기술 트렌드 공유 세미나',
      status: ReservationStatus.confirmed,
      attendeeCount: 12,
      createdAt: DateTime.now().subtract(const Duration(days: 12)),
      updatedAt: DateTime.now().subtract(const Duration(days: 5)),
    ),
    Reservation(
      id: 'res_017',
      uid: 'uid_017',
      userId: 'user_017',
      roomId: 'room_006',
      title: '인터뷰',
      startTime: DateTime.now().subtract(const Duration(days: 5, hours: 2)),
      endTime: DateTime.now().subtract(const Duration(days: 5, hours: 1)),
      purpose: '신규 직원 채용 인터뷰',
      status: ReservationStatus.confirmed,
      attendeeCount: 3,
      createdAt: DateTime.now().subtract(const Duration(days: 15)),
      updatedAt: DateTime.now().subtract(const Duration(days: 6)),
    ),
    Reservation(
      id: 'res_018',
      uid: 'uid_018',
      userId: 'user_018',
      roomId: 'room_007',
      title: 'QA 회의',
      startTime: DateTime.now().subtract(const Duration(days: 6, hours: 2)),
      endTime: DateTime.now().subtract(const Duration(days: 6, hours: 1)),
      purpose: '제품 품질 보증 검토 회의',
      status: ReservationStatus.confirmed,
      attendeeCount: 5,
      createdAt: DateTime.now().subtract(const Duration(days: 18)),
      updatedAt: DateTime.now().subtract(const Duration(days: 7)),
    ),
    Reservation(
      id: 'res_019',
      uid: 'uid_019',
      userId: 'user_019',
      roomId: 'room_008',
      title: '마케팅 전략 회의',
      startTime: DateTime.now().subtract(const Duration(days: 7, hours: 3)),
      endTime: DateTime.now().subtract(const Duration(days: 7, hours: 1)),
      purpose: '분기별 마케팅 전략 수립',
      status: ReservationStatus.confirmed,
      attendeeCount: 7,
      createdAt: DateTime.now().subtract(const Duration(days: 20)),
      updatedAt: DateTime.now().subtract(const Duration(days: 8)),
    ),
    Reservation(
      id: 'res_020',
      uid: 'uid_020',
      userId: 'user_020',
      roomId: 'room_004',
      title: '창의 아이디어 회의',
      startTime: DateTime.now().add(const Duration(minutes: 45)),
      endTime: DateTime.now().add(const Duration(hours: 1, minutes: 45)),
      purpose: '혁신적인 서비스 아이디어 브레인스토밍',
      status: ReservationStatus.confirmed,
      attendeeCount: 8,
      createdAt: DateTime.now().subtract(const Duration(hours: 24)),
      updatedAt: DateTime.now().subtract(const Duration(hours: 12)),
    ),
    Reservation(
      id: 'res_021',
      uid: 'uid_021',
      userId: 'user_021',
      roomId: 'room_006',
      title: '멘토링 세션',
      startTime: DateTime.now().add(const Duration(hours: 3)),
      endTime: DateTime.now().add(const Duration(hours: 4)),
      purpose: '주니어 개발자 멘토링',
      status: ReservationStatus.confirmed,
      attendeeCount: 2,
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      updatedAt: DateTime.now().subtract(const Duration(hours: 8)),
    ),
  ];

  static List<({Room room, Reservation reservation})> getMyBookingTestData() {
    return reservations
        .map(
          (reservation) => (
            room: DummyRooms.getRoomById(reservation.roomId),
            reservation: reservation,
          ),
        )
        .toList();
  }
}
